// Block Lab question bank (M0).
// Same two-source pattern as electronics.ts: the in-lab end-of-unit quizzes
// are absorbed from UNITS at module load (positional ids block-u<unitIdx>-c<n>
// — don't reorder the quiz arrays in units.ts), and bank-only questions are
// authored below. Block Lab units have 5 curriculum questions each, so 15
// bank-only questions bring every unit to 20.
// UNITS order is [Sequence, Loops, Nested Loops, While & If, Functions] —
// unitIdx follows that array, not the declaration order in units.ts.
// `blocksFigure` carries the QuizQ.blocks Blockly-figure DSL; the quiz-taking
// UI renders it the same way the in-lab quiz does.

import { UNITS } from '@/app/tools/block-lab/units';
import { BankQuestion, CurriculumMeta } from './types';

const CURRICULUM_META: Record<number, CurriculumMeta[]> = {
  0: [
    { topic: 'Programs & order', difficulty: 1 },
    { topic: 'Turning vs moving', difficulty: 1 },
    { topic: 'Directions', difficulty: 2 },
    { topic: 'Debugging', difficulty: 2 },
    { topic: 'Directions', difficulty: 2 },
  ],
  1: [
    { topic: 'Loop counting', difficulty: 1 },
    { topic: 'Why loops', difficulty: 1 },
    { topic: 'Loop counting', difficulty: 1 },
    { topic: 'Predicting shapes', difficulty: 2 },
    { topic: 'Nesting', difficulty: 2 },
  ],
  2: [
    { topic: 'Multiplication rule', difficulty: 2 },
    { topic: 'Nesting basics', difficulty: 2 },
    { topic: 'Patterns of patterns', difficulty: 2 },
    { topic: 'Patterns of patterns', difficulty: 2 },
    { topic: 'Multiplication rule', difficulty: 2 },
  ],
  3: [
    { topic: 'While loops', difficulty: 1 },
    { topic: 'While vs Repeat', difficulty: 2 },
    { topic: 'If blocks', difficulty: 2 },
    { topic: 'Condition order', difficulty: 3 },
    { topic: 'While vs Repeat', difficulty: 2 },
  ],
  4: [
    { topic: 'Define vs call', difficulty: 1 },
    { topic: 'Function counting', difficulty: 2 },
    { topic: 'Fix once', difficulty: 2 },
    { topic: 'Functions vs loops', difficulty: 2 },
    { topic: 'Python connection', difficulty: 1 },
  ],
};

const absorbed: BankQuestion[] = UNITS.flatMap((unit, unitIdx) =>
  unit.quiz.map((q, n) => {
    const meta = CURRICULUM_META[unitIdx]?.[n] ?? { topic: unit.title, difficulty: 2 as const };
    return {
      id: `block-u${unitIdx}-c${n}`,
      lab: 'block-lab' as const,
      unitIdx,
      topic: meta.topic,
      difficulty: meta.difficulty,
      question: q.question,
      ...(q.blocks ? { blocksFigure: q.blocks } : {}),
      options: q.options,
      answer: q.answer,
      explanation: q.explanation,
    };
  })
);

// ── Unit 1 (unitIdx 0) — Sequence: bank-only questions ───────────────────────
const UNIT1_BANK: BankQuestion[] = [
  {
    id: 'block-u0-b0',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Programs & order',
    difficulty: 1,
    question: 'What is a program?',
    options: [
      'A list of instructions the computer follows in order',
      'A drawing of a robot',
      'A kind of computer game controller',
      'A message the computer sends you',
    ],
    answer: 0,
    explanation:
      'A program is a list of instructions. The computer follows them one at a time, top to bottom, in the exact order you wrote them.',
  },
  {
    id: 'block-u0-b1',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Programs & order',
    difficulty: 1,
    question: 'Which of these is NOT one of STEM Bot’s instructions?',
    options: ['Jump Over Walls', 'Move Forward', 'Turn Left', 'Collect'],
    answer: 0,
    explanation:
      'STEM Bot knows Move Forward, Turn Left, Turn Right, and Collect. There is no jumping — walls have to be walked around!',
  },
  {
    id: 'block-u0-b2',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Collecting',
    difficulty: 1,
    question: 'What must STEM Bot do to pick up a crystal?',
    options: [
      'Stand ON the crystal’s square and use Collect',
      'Walk past the crystal quickly',
      'Look at the crystal and wait',
      'Touch the crystal with a wall',
    ],
    answer: 0,
    explanation:
      'Walking over a crystal is not enough — the bot has to stop on the crystal’s square and use the Collect block.',
  },
  {
    id: 'block-u0-b3',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Collecting',
    difficulty: 1,
    question: 'STEM Bot uses Collect on an EMPTY square. What happens?',
    options: [
      'Nothing — Collect on an empty square is safe',
      'The program crashes',
      'The bot loses a crystal',
      'A wall appears',
    ],
    answer: 0,
    explanation:
      'Collect on an empty square does nothing at all. That is handy later, when Collect goes inside loops.',
  },
  {
    id: 'block-u0-b4',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Turning vs moving',
    difficulty: 2,
    question: 'STEM Bot turns left, but stays in the same square. Which block makes it actually step forward?',
    options: ['Move Forward', 'Another Turn Left', 'Collect', 'No block — turning also moves'],
    answer: 0,
    explanation:
      'Turning only changes the direction the bot FACES. To actually move, you always need a Move Forward block after the turn.',
  },
  {
    id: 'block-u0-b5',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Directions',
    difficulty: 2,
    question: 'STEM Bot is facing the RIGHT side of the screen. After one Turn Left, which way is it facing?',
    options: ['The top of the screen', 'The bottom of the screen', 'The left side of the screen', 'Still the right side'],
    answer: 0,
    explanation:
      'Turn Left spins the bot 90° counter-clockwise — from facing the right side of the screen to facing the top.',
  },
  {
    id: 'block-u0-b6',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Directions',
    difficulty: 2,
    question: 'STEM Bot is facing the BOTTOM of the screen. After one Turn Right, which way is it facing?',
    options: ['The left side of the screen', 'The right side of the screen', 'The top of the screen', 'Still the bottom'],
    answer: 0,
    explanation:
      'Turn Right spins the bot 90° clockwise. Facing the bottom, a clockwise quarter-spin points it at the left side of the screen. Watch the arrow!',
  },
  {
    id: 'block-u0-b7',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Programs & order',
    difficulty: 1,
    question: 'What does STEM Bot do SECOND in this program?',
    blocksFigure: 'move\ncollect\nmove',
    options: ['Collect', 'Move Forward', 'Turn Right', 'Nothing'],
    answer: 0,
    explanation:
      'Top to bottom: first Move Forward, second Collect, third Move Forward. Reading order is running order.',
  },
  {
    id: 'block-u0-b8',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Debugging',
    difficulty: 2,
    question:
      'Your program works until the second turn, where STEM Bot goes the wrong way. What should you change?',
    options: [
      'Just the turn block at that spot',
      'Every block in the program',
      'The first block, no matter what it is',
      'Nothing — run it again and hope',
    ],
    answer: 0,
    explanation:
      'That is debugging: find the exact block where things went wrong and fix only that part. The rest of the program already works!',
  },
  {
    id: 'block-u0-b9',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Programs & order',
    difficulty: 3,
    question: 'Two programs use exactly the SAME blocks, but in a different order. Do they do the same thing?',
    options: [
      'No — order changes what the program does',
      'Yes — same blocks always means same result',
      'Only if they have fewer than five blocks',
      'Only on desert mazes',
    ],
    answer: 0,
    explanation:
      'Order matters! Move-then-turn puts the bot in a different place than turn-then-move. A program is its blocks AND their order.',
  },
  {
    id: 'block-u0-b10',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Debugging',
    difficulty: 1,
    question: 'What happens when STEM Bot tries to walk into a wall?',
    options: [
      'The program stops',
      'The bot breaks through the wall',
      'The bot turns around by itself',
      'The wall moves out of the way',
    ],
    answer: 0,
    explanation:
      'Walking into a wall stops the program. Look at what the bot was trying to do and fix the block that sent it there.',
  },
  {
    id: 'block-u0-b11',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Programs & order',
    difficulty: 1,
    question: 'Before you press Run, how should you read your script?',
    options: [
      'Top to bottom, like a recipe',
      'Bottom to top, like a countdown',
      'Only the first block matters',
      'You should never read it — just run it',
    ],
    answer: 0,
    explanation:
      'Read it exactly the way STEM Bot will run it: top to bottom, one block at a time, like following a recipe.',
  },
  {
    id: 'block-u0-b12',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Directions',
    difficulty: 2,
    question: 'STEM Bot is facing the TOP of the screen. After Turn Right, Turn Right, which way is it facing?',
    options: ['The bottom of the screen', 'The top of the screen', 'The left side of the screen', 'The right side of the screen'],
    answer: 0,
    explanation:
      'Each Turn Right is 90°. Two of them make a half spin (180°) — from facing the top to facing the bottom.',
  },
  {
    id: 'block-u0-b13',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Turning vs moving',
    difficulty: 3,
    question: 'STEM Bot runs: Turn Right, Turn Right, Turn Right, Turn Right. Where does it end up?',
    options: [
      'Same square, facing the same direction it started — four quarter-turns make a full spin',
      'Four squares to the right',
      'Same square, facing backwards',
      'One square forward',
    ],
    answer: 0,
    explanation:
      'Turning never moves the bot, and 4 × 90° = 360° — a complete spin back to the starting direction. Four blocks that change nothing!',
  },
  {
    id: 'block-u0-b14',
    lab: 'block-lab',
    unitIdx: 0,
    topic: 'Collecting',
    difficulty: 2,
    question: 'A crystal sits TWO squares ahead of STEM Bot. Which script collects it?',
    options: [
      'Move Forward, Move Forward, Collect',
      'Move Forward, Collect, Move Forward',
      'Collect, Move Forward, Move Forward',
      'Move Forward, Move Forward, Move Forward',
    ],
    answer: 0,
    explanation:
      'The bot must be standing ON the crystal when Collect runs — so step twice first, THEN collect.',
  },
];

// ── Unit 2 (unitIdx 1) — Loops: bank-only questions ──────────────────────────
const UNIT2_BANK: BankQuestion[] = [
  {
    id: 'block-u1-b0',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Repeat basics',
    difficulty: 1,
    question: 'What does a Repeat N block do?',
    options: [
      'Runs everything inside it exactly N times',
      'Waits N seconds',
      'Deletes N blocks',
      'Makes the bot move N squares to the side',
    ],
    answer: 0,
    explanation: 'Repeat N runs its body — the blocks inside — exactly N times, then the program continues below it.',
  },
  {
    id: 'block-u1-b1',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Repeat basics',
    difficulty: 1,
    question: 'The blocks you put INSIDE a Repeat are called the…',
    options: ['Body', 'Shell', 'Engine', 'Basket'],
    answer: 0,
    explanation: 'The body is everything inside the loop — and it can hold any blocks, even several at once.',
  },
  {
    id: 'block-u1-b2',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Why loops',
    difficulty: 1,
    question: 'A corridor is 50 cells long. Why is a loop the right tool?',
    options: [
      'One Repeat 50 { Move } replaces fifty separate Move blocks',
      'Loops make the bot walk faster',
      'Loops let the bot skip the corridor',
      'You cannot place more than 10 blocks',
    ],
    answer: 0,
    explanation:
      'Writing Move Forward fifty times is tedious and easy to miscount. Repeat 50 { Move } is two blocks and always exact.',
  },
  {
    id: 'block-u1-b3',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Loop counting',
    difficulty: 2,
    question: 'How many steps does STEM Bot take in total?',
    blocksFigure: 'repeat 5\n  move\n  move',
    options: ['10', '5', '7', '2'],
    answer: 0,
    explanation: 'The body takes 2 steps, and the loop runs it 5 times: 5 × 2 = 10 steps.',
  },
  {
    id: 'block-u1-b4',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Loop counting',
    difficulty: 2,
    question: 'How many times does Collect run?',
    blocksFigure: 'repeat 3\n  move\n  collect',
    options: ['3', '1', '6', '0'],
    answer: 0,
    explanation: 'Collect is in the body, so it runs once per lap — 3 laps, 3 Collects.',
  },
  {
    id: 'block-u1-b5',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Why loops',
    difficulty: 2,
    question: 'Your Repeat 10 { Move } program needs to walk 12 steps instead. What do you change?',
    options: [
      'Just the number on the Repeat block: 10 becomes 12',
      'Add two more Repeat blocks',
      'Rebuild the whole program',
      'Add two Turn Left blocks',
    ],
    answer: 0,
    explanation:
      'That is the power of loops: one number controls the whole pattern. Change the 10 to a 12 and you are done.',
  },
  {
    id: 'block-u1-b6',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Why loops',
    difficulty: 2,
    question: 'What in a maze is your cue to reach for a Repeat block?',
    options: [
      'The same sequence of moves appears again and again',
      'The maze has lots of walls',
      'The maze is small',
      'There are no crystals to collect',
    ],
    answer: 0,
    explanation:
      'Loops shine on repeating patterns. Spot the moves that happen over and over — that repeated chunk becomes the loop body.',
  },
  {
    id: 'block-u1-b7',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Collect inside loops',
    difficulty: 2,
    question: 'Acorns sit every 2 steps along a trail. Which loop scoops them ALL up?',
    options: [
      'Repeat { Move, Move, Collect }',
      'Repeat { Collect }',
      'Repeat { Move, Move, Move }',
      'Repeat { Turn Left, Collect }',
    ],
    answer: 0,
    explanation:
      'Two steps brings the bot onto each acorn, and Collect grabs it — a rhythm that matches the trail’s pattern exactly.',
  },
  {
    id: 'block-u1-b8',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Collect inside loops',
    difficulty: 2,
    question: 'Inside a loop, Collect sometimes runs on a square with NO acorn. Why is that okay?',
    options: [
      'Collect on an empty square is a safe no-op — nothing happens',
      'The bot places a new acorn there',
      'It is not okay — the program crashes',
      'The loop skips empty squares by itself',
    ],
    answer: 0,
    explanation:
      'Collect on an empty square does nothing, so a collecting rhythm inside a loop never breaks your program.',
  },
  {
    id: 'block-u1-b9',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Predicting shapes',
    difficulty: 3,
    question: 'What does this program make STEM Bot do?',
    blocksFigure: 'repeat 4\n  move\n  turn left',
    options: [
      'Walk a full square and end up back where it started',
      'Walk a straight line of 4 steps',
      'Zigzag across the maze',
      'Spin in place 4 times',
    ],
    answer: 0,
    explanation:
      'Each lap is one step and one 90° turn. Four laps make four sides and four corners — a complete square lap, ending at the start.',
  },
  {
    id: 'block-u1-b10',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Nesting',
    difficulty: 2,
    question: 'What is nesting?',
    options: [
      'Putting a Repeat inside another Repeat',
      'Stacking two blocks side by side',
      'Running two programs at once',
      'Hiding blocks from the toolbox',
    ],
    answer: 0,
    explanation:
      'Nesting means a loop inside a loop — the key to even more compact programs, and the star of the next unit.',
  },
  {
    id: 'block-u1-b11',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Loop counting',
    difficulty: 3,
    question: 'How many steps does STEM Bot take in total?',
    blocksFigure: 'repeat 2\n  repeat 5\n    move',
    options: ['10', '7', '5', '25'],
    answer: 0,
    explanation:
      'The inner loop takes 5 steps, and the outer loop runs it twice: 2 × 5 = 10. Nested loops multiply.',
  },
  {
    id: 'block-u1-b12',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Why loops',
    difficulty: 2,
    question: 'Two programs cross the same corridor: twelve Move blocks, or Repeat 12 { Move }. Which is easier to CHANGE later?',
    options: [
      'The Repeat — one number controls the length',
      'The twelve Move blocks — more blocks means more control',
      'They are equally easy to change',
      'Neither can ever be changed',
    ],
    answer: 0,
    explanation:
      'To make the loop version longer you edit one number. The block-by-block version means counting, adding, and re-checking every block.',
  },
  {
    id: 'block-u1-b13',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Predicting shapes',
    difficulty: 3,
    question: 'Every stair of a staircase takes the same 4 blocks. What is the fewest-block way to climb 3 stairs?',
    options: [
      'Put the 4 stair blocks inside a Repeat 3',
      'Write the 4 blocks out three times in a row',
      'Use Repeat 12 { Move }',
      'Use three separate Repeat 1 loops',
    ],
    answer: 0,
    explanation:
      'The stair is the repeating pattern, so it becomes the loop body. Repeat 3 stamps it three times — 5 blocks instead of 12.',
  },
  {
    id: 'block-u1-b14',
    lab: 'block-lab',
    unitIdx: 1,
    topic: 'Repeat basics',
    difficulty: 1,
    question: 'Can a Repeat body hold MORE than one block?',
    options: [
      'Yes — the body can contain any blocks, even several',
      'No — exactly one block per loop',
      'Only Move blocks are allowed inside',
      'Only if the number is bigger than 5',
    ],
    answer: 0,
    explanation:
      'The body can be a whole sequence — moves, turns, Collects, even another loop. The loop runs the entire body each lap.',
  },
];

// ── Unit 3 (unitIdx 2) — Nested Loops: bank-only questions ───────────────────
const UNIT3_BANK: BankQuestion[] = [
  {
    id: 'block-u2-b0',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Nesting basics',
    difficulty: 1,
    question: 'What is a nested loop?',
    options: [
      'A loop whose body contains another loop',
      'A loop that never stops',
      'Two loops side by side',
      'A loop with no body',
    ],
    answer: 0,
    explanation:
      'Nesting means the body of one loop holds another loop. The inner pattern runs completely on every lap of the outer loop.',
  },
  {
    id: 'block-u2-b1',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Multiplication rule',
    difficulty: 2,
    question: 'How many steps does STEM Bot take?',
    blocksFigure: 'repeat 5\n  repeat 2\n    move',
    options: ['10', '7', '2', '52'],
    answer: 0,
    explanation: 'Inner loop: 2 steps. Outer loop runs it 5 times: 5 × 2 = 10 steps.',
  },
  {
    id: 'block-u2-b2',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Nesting basics',
    difficulty: 2,
    question: 'What is the best way to READ a nested loop?',
    options: [
      'From the inside out — understand the inner loop first',
      'From the outside in — the inner loop does not matter',
      'Bottom to top',
      'Skip the loops and read only the moves',
    ],
    answer: 0,
    explanation:
      'Work out what the inner loop does first (one side, one row…), then see how many times the outer loop stamps it.',
  },
  {
    id: 'block-u2-b3',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Multiplication rule',
    difficulty: 2,
    question: 'Without running it, what math predicts a nested loop’s total moves?',
    options: [
      'Multiply: inner repeats × outer repeats',
      'Add: inner repeats + outer repeats',
      'Subtract the inner from the outer',
      'You cannot predict it without running',
    ],
    answer: 0,
    explanation:
      'The inner loop runs ALL its repeats during EACH outer repeat — so the counts multiply. If you can multiply, you can predict.',
  },
  {
    id: 'block-u2-b4',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Patterns of patterns',
    difficulty: 2,
    question: 'Which plan traces a square?',
    options: [
      'Repeat 4 { one side of steps, then a turn }',
      'Repeat 4 { turn, turn }',
      'One giant Repeat 16 { Move }',
      'Move blocks with no turns',
    ],
    answer: 0,
    explanation:
      'A square is 4 × (one side + one corner). The side is the inner pattern; the outer Repeat 4 stamps it around the square.',
  },
  {
    id: 'block-u2-b5',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'If on acorn',
    difficulty: 1,
    question: 'What does the "If on an acorn" block do?',
    options: [
      'Runs its blocks only when STEM Bot is standing on an acorn',
      'Makes acorns appear',
      'Counts every acorn in the maze',
      'Turns the bot toward the nearest acorn',
    ],
    answer: 0,
    explanation:
      'It is your first if — a question inside the program. Standing on an acorn? Run the blocks. Not standing on one? Skip them.',
  },
  {
    id: 'block-u2-b6',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'If on acorn',
    difficulty: 3,
    question: 'What does STEM Bot do on EACH lap of this loop?',
    blocksFigure: 'repeat 6\n  move\n  if acorn\n    collect',
    options: [
      'Takes a step, then collects only if an acorn is really there',
      'Collects six acorns before moving',
      'Moves six squares, then collects once at the end',
      'Asks the player what to do',
    ],
    answer: 0,
    explanation:
      'Each lap: step, then CHECK. The loop runs a fixed 6 times, but every lap can decide something — that is a decision inside a loop.',
  },
  {
    id: 'block-u2-b7',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Patterns of patterns',
    difficulty: 3,
    question: 'The classic mowing bug: after the U-turn, the second row runs…',
    options: [
      'In the OPPOSITE direction from the first row',
      'In the same direction as the first row',
      'Twice as fast',
      'Backwards, undoing the first row',
    ],
    answer: 0,
    explanation:
      'Mowing goes back and forth: row right, U-turn, row LEFT. Walk it with your finger before you code — if two rows work, the outer loop mows the field.',
  },
  {
    id: 'block-u2-b8',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Patterns of patterns',
    difficulty: 2,
    question: 'Mowing a whole field with nested loops means…',
    options: [
      'Rows × (one row plus a U-turn)',
      'One loop with a thousand Moves',
      'A turn block for every blade of grass',
      'Collect blocks only',
    ],
    answer: 0,
    explanation:
      'The row-plus-U-turn is the inner pattern; the outer loop stamps it once per row. Big jobs are patterns OF patterns.',
  },
  {
    id: 'block-u2-b9',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Multiplication rule',
    difficulty: 3,
    question: 'How many times does STEM Bot TURN in this program?',
    blocksFigure: 'repeat 3\n  repeat 4\n    move\n  turn right',
    options: ['3', '4', '12', '7'],
    answer: 0,
    explanation:
      'Watch WHERE the turn sits: outside the inner loop, inside the outer one. It runs once per outer lap — 3 times. (The moves run 3 × 4 = 12 times.)',
  },
  {
    id: 'block-u2-b10',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Nesting basics',
    difficulty: 2,
    question: 'During ONE repeat of the outer loop, how much of the inner loop runs?',
    options: [
      'All of its repeats, completely',
      'Just one of its repeats',
      'Half of its repeats',
      'None — inner loops only run at the end',
    ],
    answer: 0,
    explanation:
      'The inner loop finishes ALL of its laps before the outer loop moves on. That is why the counts multiply.',
  },
  {
    id: 'block-u2-b11',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Patterns of patterns',
    difficulty: 3,
    question: 'Your nested-loop square has sides of 2. To make sides of 3, what do you change?',
    options: [
      'One number — the inner loop’s repeat count',
      'The whole program',
      'The outer loop only',
      'You must switch back to single blocks',
    ],
    answer: 0,
    explanation:
      'The inner loop draws one side, so its number IS the side length. Change 2 to 3 and the whole square grows — the power of nesting.',
  },
  {
    id: 'block-u2-b12',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'If on acorn',
    difficulty: 2,
    question: 'STEM Bot is NOT standing on an acorn when "If on an acorn" runs. What happens to the blocks inside the if?',
    options: [
      'They are skipped this time',
      'They run anyway',
      'They run twice on the next lap',
      'The program stops',
    ],
    answer: 0,
    explanation:
      'An if only runs its blocks when its condition is true. No acorn means the body is skipped, and the program moves on.',
  },
  {
    id: 'block-u2-b13',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Multiplication rule',
    difficulty: 3,
    question: 'How many times does Collect run?',
    blocksFigure: 'repeat 2\n  move\n  repeat 3\n    collect',
    options: ['6', '3', '2', '5'],
    answer: 0,
    explanation:
      'Collect sits in the inner loop: 3 per outer lap × 2 outer laps = 6. (Move sits OUTSIDE the inner loop, so it only runs twice.)',
  },
  {
    id: 'block-u2-b14',
    lab: 'block-lab',
    unitIdx: 2,
    topic: 'Patterns of patterns',
    difficulty: 1,
    question: 'Why do programmers nest loops?',
    options: [
      'Big jobs are usually patterns OF patterns — squares, staircases, fields of rows',
      'Nested programs run in slow motion',
      'It is the only way to use Collect',
      'Nesting makes the maze smaller',
    ],
    answer: 0,
    explanation:
      'Write the small pattern once as the inner loop, and let the outer loop stamp it across the maze. Block counts crash — check the pars!',
  },
];

// ── Unit 4 (unitIdx 3) — While & If: bank-only questions ─────────────────────
const UNIT4_BANK: BankQuestion[] = [
  {
    id: 'block-u3-b0',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Sensors',
    difficulty: 1,
    question: 'What do sensors let STEM Bot do?',
    options: [
      'Check its surroundings while the program runs',
      'Move faster through corridors',
      'See the whole maze map at once',
      'Skip walls',
    ],
    answer: 0,
    explanation:
      'Sensors check things at runtime — is there a path ahead? a chip underfoot? — so the bot can react instead of blindly counting.',
  },
  {
    id: 'block-u3-b1',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'While loops',
    difficulty: 1,
    question: 'A while loop keeps running its body…',
    options: [
      'As long as its condition is true',
      'Exactly 10 times',
      'Until you press Stop',
      'One time only',
    ],
    answer: 0,
    explanation:
      'While loops run on conditions, not counts. Every lap the condition is checked — false means the loop is done.',
  },
  {
    id: 'block-u3-b2',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'While loops',
    difficulty: 2,
    question: 'When does "While not at goal { Move }" stop?',
    options: [
      'When STEM Bot reaches the goal',
      'After exactly 10 moves',
      'When the bot collects a chip',
      'It never stops',
    ],
    answer: 0,
    explanation:
      '"Not at goal" becomes false the moment the bot arrives — and the loop ends. No counting, no matter how long the road.',
  },
  {
    id: 'block-u3-b3',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'If blocks',
    difficulty: 2,
    question: 'When its condition is true, how many times does an IF block run its body?',
    options: ['Once', 'Over and over, like a loop', 'Twice', 'Zero times'],
    answer: 0,
    explanation:
      'An if is a one-time check, not a loop. Condition true → body runs once. Put the if INSIDE a loop to check again on every lap.',
  },
  {
    id: 'block-u3-b4',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'While vs Repeat',
    difficulty: 2,
    question: 'The station’s corridors rearrange themselves on every visit. Why do sensors beat counting here?',
    options: [
      'A sensor program adapts to whatever the maze looks like; counted steps only fit one layout',
      'Sensors make the bot walk faster',
      'Counting is against the station rules',
      'Sensors collect chips automatically',
    ],
    answer: 0,
    explanation:
      'When you cannot know the layout in advance, fixed counts are useless. Conditions let the same program solve many different mazes.',
  },
  {
    id: 'block-u3-b5',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Infinite loops',
    difficulty: 3,
    question: 'What happens if a while loop’s condition NEVER becomes false?',
    options: [
      'The loop runs forever (until the safety limit stops it)',
      'The loop skips itself',
      'The program finishes normally',
      'The condition fixes itself',
    ],
    answer: 0,
    explanation:
      'That is an infinite loop. Always make sure the body actually makes progress toward ending the condition — like moving toward the goal.',
  },
  {
    id: 'block-u3-b6',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Sensors',
    difficulty: 2,
    question: 'What does "If on a data chip → Collect" do inside a loop?',
    options: [
      'Checks each square and collects only when a chip is really there',
      'Collects every chip in the maze at once',
      'Places new chips on the floor',
      'Stops the loop at the first chip',
    ],
    answer: 0,
    explanation:
      'Every lap the bot asks: am I on a chip? If yes, collect. It is the cleanest way to grab everything the bot crosses.',
  },
  {
    id: 'block-u3-b7',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Condition order',
    difficulty: 2,
    question: 'The if blocks inside a while loop run…',
    options: [
      'In order, top to bottom, on every single lap',
      'In whatever order the bot prefers',
      'Only once, at the start',
      'All at the same time',
    ],
    answer: 0,
    explanation:
      'Every lap of the loop, the ifs are checked top to bottom. That order IS part of your program — and later mazes prove it.',
  },
  {
    id: 'block-u3-b8',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Condition order',
    difficulty: 3,
    question: 'In a ring maze, why should "If path left → Turn Left" come BEFORE "If path ahead → Move"?',
    options: [
      'If moving ahead is checked first, the bot sails past the doorway and circles forever',
      'Turn blocks always have to be first in every program',
      'Left is more important than ahead in space',
      'It does not matter — any order works everywhere',
    ],
    answer: 0,
    explanation:
      'At the doorway, BOTH conditions are true. Whichever if fires first wins — so charging ahead first means the turn never gets its moment.',
  },
  {
    id: 'block-u3-b9',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'While vs Repeat',
    difficulty: 2,
    question: 'One sensor program solves a short corridor AND a much longer one. How?',
    options: [
      'The while loop just runs more laps on the longer corridor — conditions adapt',
      'The program secretly rewrites itself',
      'Long corridors are not allowed',
      'It cannot — you always need two programs',
    ],
    answer: 0,
    explanation:
      '"While path ahead { Move }" takes as many steps as the corridor needs — 8 or 800. Same code, any length. Counting cannot do that.',
  },
  {
    id: 'block-u3-b10',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'If blocks',
    difficulty: 2,
    question: 'What is the difference between an IF and a WHILE?',
    options: [
      'If checks once and runs its body at most once; while keeps repeating as long as its condition is true',
      'They are two names for the same block',
      'If is for turning, while is for moving',
      'While can only be used once per program',
    ],
    answer: 0,
    explanation:
      'If = a single decision. While = a repeating one. Put ifs inside a while and you get decision logic that runs lap after lap.',
  },
  {
    id: 'block-u3-b11',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Sensors',
    difficulty: 1,
    question: '"While path ahead" is true when…',
    options: [
      'There is an open cell directly in front of STEM Bot',
      'The bot is standing on a chip',
      'The bot has reached the goal',
      'There is a wall directly ahead',
    ],
    answer: 0,
    explanation:
      'This sensor feels the cell straight ahead. Open cell → true, keep going. Wall → false, the loop ends.',
  },
  {
    id: 'block-u3-b12',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Condition order',
    difficulty: 3,
    question: 'Two programs use the SAME if blocks inside the same while loop, just in a different order. Are they the same program?',
    options: [
      'No — the order of conditions changes what the bot does',
      'Yes — same blocks, same behavior',
      'Only in ring mazes',
      'Only if there are exactly three ifs',
    ],
    answer: 0,
    explanation:
      'Ordering is a real programming decision. The Loop Trap and Mirror Trap mazes are solved or lost purely by which check comes first.',
  },
  {
    id: 'block-u3-b13',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'Condition order',
    difficulty: 3,
    question: 'A maze’s path turns LEFT twice, but this is the whole program. What happens?',
    blocksFigure: 'while goal\n  if ahead\n    move\n  if right\n    turn right',
    options: [
      'STEM Bot gets stuck — nothing in the loop handles a left turn',
      'The bot turns left automatically when it must',
      'The bot solves the maze anyway',
      'The right turns become left turns',
    ],
    answer: 0,
    explanation:
      'The loop only knows "move ahead" and "turn right." At a left corner both checks fail, nothing changes, and the bot stops making progress. Your ifs must cover the turns the maze actually has.',
  },
  {
    id: 'block-u3-b14',
    lab: 'block-lab',
    unitIdx: 3,
    topic: 'While vs Repeat',
    difficulty: 1,
    question: 'Which program can cross a corridor whose length you DON’T know?',
    options: [
      'While path ahead { Move Forward }',
      'Repeat 10 { Move Forward }',
      'Move Forward written 10 times',
      'Turn Right, then Collect',
    ],
    answer: 0,
    explanation:
      'Only a condition can handle the unknown: the while loop keeps stepping while the path is open, however long that takes.',
  },
];

// ── Unit 5 (unitIdx 4) — Functions: bank-only questions ──────────────────────
const UNIT5_BANK: BankQuestion[] = [
  {
    id: 'block-u4-b0',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Define vs call',
    difficulty: 1,
    question: 'What is a function?',
    options: [
      'A named set of blocks you can run by calling its name',
      'A block that moves the bot faster',
      'A special kind of wall',
      'A loop that runs forever',
    ],
    answer: 0,
    explanation:
      'A function gives a name to a group of blocks. Define it once, then call it by name wherever you need it.',
  },
  {
    id: 'block-u4-b1',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Define vs call',
    difficulty: 1,
    question: 'Which block actually RUNS the blocks inside a function?',
    options: ['Call Function', 'Define Function', 'Repeat', 'Collect'],
    answer: 0,
    explanation:
      'Define only gets the function ready — it runs nothing by itself. Call Function is what makes the blocks happen.',
  },
  {
    id: 'block-u4-b2',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Function counting',
    difficulty: 2,
    question: 'How many times does STEM Bot TURN in this program?',
    blocksFigure: 'define 1\n  move\n  turn right\ncall 1\ncall 1',
    options: ['2', '1', '3', '0'],
    answer: 0,
    explanation:
      'Each call runs the whole function once — 1 turn per call, 2 calls, 2 turns. (The definition itself runs nothing.)',
  },
  {
    id: 'block-u4-b3',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Fix once',
    difficulty: 2,
    question: 'Why does fixing ONE definition repair every call at once?',
    options: [
      'Every call runs the definition — there is only one copy of the blocks',
      'The calls copy themselves when you fix them',
      'It does not — you must fix each call',
      'Functions cannot have mistakes',
    ],
    answer: 0,
    explanation:
      'Calls do not contain their own blocks; they all point at the same definition. One fix there, and every call is instantly correct.',
  },
  {
    id: 'block-u4-b4',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Functions vs loops',
    difficulty: 2,
    question: 'For your block count (par), how much does one Call Function cost?',
    options: [
      'One block — no matter how big the function is',
      'As many blocks as the function contains',
      'Two blocks — one to start, one to stop',
      'Zero, but only the first time',
    ],
    answer: 0,
    explanation:
      'A call counts as ONE block even if the function holds twenty. Write once, call anywhere — and watch your pars drop.',
  },
  {
    id: 'block-u4-b5',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Functions + everything',
    difficulty: 2,
    question: 'Can you put a Call Function inside a Repeat loop?',
    options: [
      'Yes — the loop calls the function on every lap',
      'No — calls must be at the top of the program',
      'Only if the function is empty',
      'Only in desert mazes',
    ],
    answer: 0,
    explanation:
      '"Repeat 4 { Call Function 1 }" runs the function four times. Functions work with every tool you already have.',
  },
  {
    id: 'block-u4-b6',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Functions + everything',
    difficulty: 3,
    question: 'Can Function 2 call Function 1 from inside itself?',
    options: [
      'Yes — bigger patterns can be built from smaller ones',
      'No — functions can never touch each other',
      'Only if they have the same blocks',
      'Only once per program',
    ],
    answer: 0,
    explanation:
      'A function’s body can hold anything — including a call to another function. That is how small patterns compose into big ones.',
  },
  {
    id: 'block-u4-b7',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Define vs call',
    difficulty: 2,
    question: 'Your program has Define Function 1 and Define Function 2 — and nothing else. Why does STEM Bot sit still when you press Run?',
    options: [
      'Definitions run nothing by themselves — there are no Call blocks',
      'Two functions cancel each other out',
      'The bot is waiting for a password',
      'Functions only work after Unit 6',
    ],
    answer: 0,
    explanation:
      'The #1 beginner mistake: all definitions, no calls. A definition just waits to be asked. Define, THEN call.',
  },
  {
    id: 'block-u4-b8',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Python connection',
    difficulty: 2,
    question: 'In Python, after defining a function with def, how do you run it?',
    options: [
      'Call it by name — like stair()',
      'Write def again',
      'Draw its blocks',
      'Python functions run by themselves',
    ],
    answer: 0,
    explanation:
      'Exactly like Call Function: you call the function by its name. Same idea, same words — you already know how it works.',
  },
  {
    id: 'block-u4-b9',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Fix once',
    difficulty: 2,
    question: 'Why do named functions make a long program easier to READ?',
    options: [
      'Names tell the story — "stair, walk, stair" reads better than 20 raw blocks',
      'Names make the blocks smaller on screen',
      'Reading is not important in programming',
      'Functions hide the program from other people',
    ],
    answer: 0,
    explanation:
      'A good name says what a chunk of code DOES. Your program becomes a story of named steps instead of a wall of blocks.',
  },
  {
    id: 'block-u4-b10',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Function counting',
    difficulty: 3,
    question: 'How many times does STEM Bot move forward?',
    blocksFigure: 'define 1\n  move\n  move\nrepeat 3\n  call 1',
    options: ['6', '2', '3', '5'],
    answer: 0,
    explanation:
      'The loop calls the function 3 times, and each call is 2 moves: 3 × 2 = 6. A call inside a loop — two tools working together.',
  },
  {
    id: 'block-u4-b11',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Define vs call',
    difficulty: 1,
    question: 'Programmers say it in two words: first you ______ a function, then you ______ it.',
    options: ['define … call', 'call … define', 'build … break', 'move … collect'],
    answer: 0,
    explanation:
      'Define, then call. That is the real vocabulary — the same words you will use in Python and every other language.',
  },
  {
    id: 'block-u4-b12',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Fix once',
    difficulty: 3,
    question:
      'Your stair function forgot its Collect block, and you already call it in 4 places. What is the best fix?',
    options: [
      'Add Collect inside the ONE definition — all 4 calls are fixed instantly',
      'Add a Collect after each of the 4 calls',
      'Delete the function and write the stairs out by hand',
      'Call the function a 5th time',
    ],
    answer: 0,
    explanation:
      'One definition, one fix. Adding Collect after every call works but costs 4 blocks and 4 chances for a mistake — fix the source instead.',
  },
  {
    id: 'block-u4-b13',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Functions vs loops',
    difficulty: 2,
    question: 'When is a function BETTER than a Repeat?',
    options: [
      'When the same pattern appears in scattered places, with other moves in between',
      'When the pattern repeats back-to-back in one spot',
      'Functions are always worse than Repeats',
      'Only when the maze has no crystals',
    ],
    answer: 0,
    explanation:
      'Repeat replays its body in ONE place. A function has a name, so you can call it at the start, the end, or anywhere between.',
  },
  {
    id: 'block-u4-b14',
    lab: 'block-lab',
    unitIdx: 4,
    topic: 'Python connection',
    difficulty: 1,
    question: 'Block Lab functions prepare you for which real programming language keyword?',
    options: ['def', 'wall', 'bot', 'maze'],
    answer: 0,
    explanation:
      'Python defines functions with def — def stair(): — and calls them by name. You are already writing real code.',
  },
];

export const BLOCK_BANK: BankQuestion[] = [
  ...absorbed,
  ...UNIT1_BANK,
  ...UNIT2_BANK,
  ...UNIT3_BANK,
  ...UNIT4_BANK,
  ...UNIT5_BANK,
];
